server:
  port: 8005
spring:
  application:
    name: springbootfeign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
zuul:
  ignoredServices: '*'
  routes:
    springboot1: /users/**